import "./globals.css";
import { permanentRedirect } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return permanentRedirect("https://www.htecsa.com", "push")
}